import os

paths = [
    # root files
    "README.md",
    ".gitignore",
    ".env.example",
    "docker-compose.yml",
    "docker-compose.prod.yml",
    "Makefile",

    # docs/
    "docs/architecture/system-overview.md",
    "docs/architecture/queue-state-machine.md",
    "docs/architecture/ai-agent-flow.md",
    "docs/architecture/rag-pipeline.md",
    "docs/api/rest-api.md",
    "docs/api/websocket-events.md",
    "docs/api/chatbot-api.md",
    "docs/design/color-system.md",
    "docs/design/ui-screens.md",
    "docs/deployment/aws-setup.md",
    "docs/deployment/github-actions.md",

    # .github/workflows/
    ".github/workflows/mobile-build.yml",
    ".github/workflows/web-build.yml",
    ".github/workflows/backend-test.yml",
    ".github/workflows/ai-test.yml",
    ".github/workflows/chatbot-test.yml",
    ".github/workflows/deploy-aws.yml",

    # mobile/
    "mobile/pubspec.yaml",
    "mobile/analysis_options.yaml",
    "mobile/android/.gitkeep",
    "mobile/ios/.gitkeep",
    "mobile/assets/images/.gitkeep",
    "mobile/assets/icons/.gitkeep",
    "mobile/assets/fonts/.gitkeep",
    "mobile/assets/animations/.gitkeep",
    "mobile/lib/main.dart",
    "mobile/lib/app.dart",
    "mobile/lib/core/config/env.dart",
    "mobile/lib/core/config/api_config.dart",
    "mobile/lib/core/config/firebase_config.dart",
    "mobile/lib/core/theme/colors.dart",
    "mobile/lib/core/theme/typography.dart",
    "mobile/lib/core/theme/app_theme.dart",
    "mobile/lib/core/constants/.gitkeep",
    "mobile/lib/core/utils/date_utils.dart",
    "mobile/lib/core/utils/token_utils.dart",
    "mobile/lib/core/errors/exceptions.dart",
    "mobile/lib/core/errors/error_handler.dart",
    "mobile/lib/data/models/user_model.dart",
    "mobile/lib/data/models/institution_model.dart",
    "mobile/lib/data/models/queue_model.dart",
    "mobile/lib/data/models/token_model.dart",
    "mobile/lib/data/models/chat_message_model.dart",
    "mobile/lib/data/datasources/remote/api_client.dart",
    "mobile/lib/data/datasources/remote/auth_api.dart",
    "mobile/lib/data/datasources/remote/queue_api.dart",
    "mobile/lib/data/datasources/remote/institution_api.dart",
    "mobile/lib/data/datasources/remote/prediction_api.dart",
    "mobile/lib/data/datasources/remote/chatbot_api.dart",
    "mobile/lib/data/datasources/local/secure_storage.dart",
    "mobile/lib/data/datasources/local/cache_storage.dart",
    "mobile/lib/data/repositories/auth_repository.dart",
    "mobile/lib/data/repositories/queue_repository.dart",
    "mobile/lib/data/repositories/chatbot_repository.dart",
    "mobile/lib/domain/entities/.gitkeep",
    "mobile/lib/domain/repositories/.gitkeep",
    "mobile/lib/domain/usecases/join_queue_usecase.dart",
    "mobile/lib/domain/usecases/cancel_queue_usecase.dart",
    "mobile/lib/domain/usecases/get_prediction_usecase.dart",
    "mobile/lib/presentation/providers/auth_provider.dart",
    "mobile/lib/presentation/providers/queue_provider.dart",
    "mobile/lib/presentation/providers/chat_provider.dart",
    "mobile/lib/presentation/providers/notification_provider.dart",
    "mobile/lib/presentation/screens/splash/.gitkeep",
    "mobile/lib/presentation/screens/onboarding/.gitkeep",
    "mobile/lib/presentation/screens/auth/login_screen.dart",
    "mobile/lib/presentation/screens/auth/register_screen.dart",
    "mobile/lib/presentation/screens/auth/otp_screen.dart",
    "mobile/lib/presentation/screens/home/home_screen.dart",
    "mobile/lib/presentation/screens/institution/search_screen.dart",
    "mobile/lib/presentation/screens/institution/detail_screen.dart",
    "mobile/lib/presentation/screens/queue/join_queue_screen.dart",
    "mobile/lib/presentation/screens/queue/live_tracking_screen.dart",
    "mobile/lib/presentation/screens/queue/token_screen.dart",
    "mobile/lib/presentation/screens/my_queues/.gitkeep",
    "mobile/lib/presentation/screens/history/.gitkeep",
    "mobile/lib/presentation/screens/profile/.gitkeep",
    "mobile/lib/presentation/screens/chatbot/chat_screen.dart",
    "mobile/lib/presentation/screens/chatbot/widgets/chat_bubble.dart",
    "mobile/lib/presentation/screens/chatbot/widgets/chat_input.dart",
    "mobile/lib/presentation/screens/chatbot/widgets/queue_card_message.dart",
    "mobile/lib/presentation/screens/chatbot/widgets/typing_indicator.dart",
    "mobile/lib/presentation/screens/notifications/.gitkeep",
    "mobile/lib/presentation/widgets/common/.gitkeep",
    "mobile/lib/presentation/widgets/queue/.gitkeep",
    "mobile/lib/presentation/widgets/chatbot/.gitkeep",
    "mobile/lib/services/websocket_service.dart",
    "mobile/lib/services/notification_service.dart",
    "mobile/lib/services/location_service.dart",
    "mobile/lib/services/chatbot_service.dart",
    "mobile/test/unit/.gitkeep",
    "mobile/test/widget/.gitkeep",
    "mobile/test/integration/.gitkeep",

    # web/
    "web/package.json",
    "web/vite.config.ts",
    "web/tsconfig.json",
    "web/index.html",
    "web/public/.gitkeep",
    "web/src/main.tsx",
    "web/src/App.tsx",
    "web/src/router/index.tsx",
    "web/src/router/staff-routes.tsx",
    "web/src/router/admin-routes.tsx",
    "web/src/config/env.ts",
    "web/src/config/api.config.ts",
    "web/src/theme/colors.ts",
    "web/src/theme/typography.ts",
    "web/src/theme/index.ts",
    "web/src/layouts/StaffLayout.tsx",
    "web/src/layouts/AdminLayout.tsx",
    "web/src/layouts/AuthLayout.tsx",
    "web/src/pages/auth/.gitkeep",
    "web/src/pages/staff/Dashboard.tsx",
    "web/src/pages/staff/LiveQueue.tsx",
    "web/src/pages/staff/Counters.tsx",
    "web/src/pages/staff/VerifyCustomer.tsx",
    "web/src/pages/staff/TokenActions.tsx",
    "web/src/pages/staff/ChatbotPanel.tsx",
    "web/src/pages/admin/Dashboard.tsx",
    "web/src/pages/admin/LiveQueuesMonitor.tsx",
    "web/src/pages/admin/Counters.tsx",
    "web/src/pages/admin/Customers.tsx",
    "web/src/pages/admin/Staff.tsx",
    "web/src/pages/admin/Services.tsx",
    "web/src/pages/admin/Analytics.tsx",
    "web/src/pages/admin/Reports.tsx",
    "web/src/pages/admin/MIS.tsx",
    "web/src/pages/admin/Settings.tsx",
    "web/src/pages/admin/ChatbotConsole.tsx",
    "web/src/pages/chatbot/.gitkeep",
    "web/src/components/common/.gitkeep",
    "web/src/components/queue/.gitkeep",
    "web/src/components/charts/.gitkeep",
    "web/src/components/chatbot/ChatWidget.tsx",
    "web/src/components/chatbot/ChatWindow.tsx",
    "web/src/components/chatbot/MessageList.tsx",
    "web/src/components/chatbot/QuickReplies.tsx",
    "web/src/hooks/useAuth.ts",
    "web/src/hooks/useWebSocket.ts",
    "web/src/hooks/useChat.ts",
    "web/src/hooks/useAnalytics.ts",
    "web/src/services/api/axios.ts",
    "web/src/services/api/auth.api.ts",
    "web/src/services/api/queue.api.ts",
    "web/src/services/api/chatbot.api.ts",
    "web/src/services/api/analytics.api.ts",
    "web/src/services/websocket/socket.ts",
    "web/src/store/authStore.ts",
    "web/src/store/queueStore.ts",
    "web/src/store/chatStore.ts",
    "web/src/utils/.gitkeep",
    "web/tests/unit/.gitkeep",
    "web/tests/e2e/.gitkeep",

    # backend/
    "backend/requirements.txt",
    "backend/pyproject.toml",
    "backend/Dockerfile",
    "backend/alembic.ini",
    "backend/app/main.py",
    "backend/app/core/config.py",
    "backend/app/core/security.py",
    "backend/app/core/database.py",
    "backend/app/core/redis_client.py",
    "backend/app/core/websocket_manager.py",
    "backend/app/core/celery_app.py",
    "backend/app/core/logging.py",
    "backend/app/api/v1/__init__.py",
    "backend/app/api/v1/auth.py",
    "backend/app/api/v1/institutions.py",
    "backend/app/api/v1/services.py",
    "backend/app/api/v1/queues.py",
    "backend/app/api/v1/tokens.py",
    "backend/app/api/v1/counters.py",
    "backend/app/api/v1/staff.py",
    "backend/app/api/v1/prediction.py",
    "backend/app/api/v1/chatbot.py",
    "backend/app/api/v1/analytics.py",
    "backend/app/api/v1/reports.py",
    "backend/app/api/v1/notifications.py",
    "backend/app/api/v1/websocket.py",
    "backend/app/api/deps.py",
    "backend/app/models/user.py",
    "backend/app/models/institution.py",
    "backend/app/models/service.py",
    "backend/app/models/queue.py",
    "backend/app/models/token.py",
    "backend/app/models/counter.py",
    "backend/app/models/staff.py",
    "backend/app/models/analytics.py",
    "backend/app/models/chat_session.py",
    "backend/app/models/chat_message.py",
    "backend/app/models/document.py",
    "backend/app/schemas/auth.py",
    "backend/app/schemas/institution.py",
    "backend/app/schemas/queue.py",
    "backend/app/schemas/token.py",
    "backend/app/schemas/prediction.py",
    "backend/app/schemas/chatbot.py",
    "backend/app/schemas/analytics.py",
    "backend/app/services/auth_service.py",
    "backend/app/services/institution_service.py",
    "backend/app/services/queue_service.py",
    "backend/app/services/token_service.py",
    "backend/app/services/state_machine.py",
    "backend/app/services/grace_period_service.py",
    "backend/app/services/prediction_service.py",
    "backend/app/services/chatbot_service.py",
    "backend/app/services/notification_service.py",
    "backend/app/services/analytics_service.py",
    "backend/app/services/report_service.py",
    "backend/app/workers/expiry_worker.py",
    "backend/app/workers/reminder_worker.py",
    "backend/app/workers/notification_worker.py",
    "backend/app/workers/prediction_worker.py",
    "backend/app/workers/analytics_worker.py",
    "backend/app/vectorstore/embeddings.py",
    "backend/app/vectorstore/retriever.py",
    "backend/app/vectorstore/indexer.py",
    "backend/app/utils/jwt_utils.py",
    "backend/app/utils/datetime_utils.py",
    "backend/app/utils/validators.py",
    "backend/alembic/env.py",
    "backend/alembic/versions/001_create_users.py",
    "backend/alembic/versions/002_create_institutions.py",
    "backend/alembic/versions/003_create_queues.py",
    "backend/alembic/versions/004_create_tokens.py",
    "backend/alembic/versions/005_create_chat_tables.py",
    "backend/alembic/versions/006_enable_pgvector.py",
    "backend/seeds/seed_institutions.py",
    "backend/seeds/seed_services.py",
    "backend/seeds/seed_faq_docs.py",
    "backend/tests/unit/.gitkeep",
    "backend/tests/integration/.gitkeep",
    "backend/tests/conftest.py",

    # ai/
    "ai/requirements.txt",
    "ai/Dockerfile",
    "ai/prediction/train.py",
    "ai/prediction/predict.py",
    "ai/prediction/features.py",
    "ai/prediction/evaluate.py",
    "ai/prediction/dataset_builder.py",
    "ai/prediction/models/wait_time_model.pkl",
    "ai/prediction/models/metadata.json",
    "ai/agents/graph.py",
    "ai/agents/state.py",
    "ai/agents/nodes/intent_node.py",
    "ai/agents/nodes/retrieve_node.py",
    "ai/agents/nodes/tool_node.py",
    "ai/agents/nodes/predict_node.py",
    "ai/agents/nodes/respond_node.py",
    "ai/agents/tools/queue_tool.py",
    "ai/agents/tools/prediction_tool.py",
    "ai/agents/tools/institution_tool.py",
    "ai/agents/tools/rag_tool.py",
    "ai/agents/memory/conversation_memory.py",
    "ai/rag/ingest.py",
    "ai/rag/chunker.py",
    "ai/rag/embedder.py",
    "ai/rag/retriever.py",
    "ai/rag/sources/faq_docs/.gitkeep",
    "ai/rag/sources/institution_info/.gitkeep",
    "ai/rag/sources/service_guides/.gitkeep",
    "ai/notebooks/wait_time_experiments.ipynb",
    "ai/notebooks/agent_testing.ipynb",
    "ai/tests/.gitkeep",

    # chatbot/
    "chatbot/requirements.txt",
    "chatbot/Dockerfile",
    "chatbot/app/main.py",
    "chatbot/app/config.py",
    "chatbot/app/llm/provider.py",
    "chatbot/app/llm/prompts.py",
    "chatbot/app/llm/system_prompt.txt",
    "chatbot/app/agent/runner.py",
    "chatbot/app/agent/context_builder.py",
    "chatbot/app/channels/in_app.py",
    "chatbot/app/channels/web_widget.py",
    "chatbot/app/channels/whatsapp.py",
    "chatbot/app/session/manager.py",
    "chatbot/app/session/store.py",
    "chatbot/app/api/chat.py",
    "chatbot/app/api/feedback.py",
    "chatbot/app/utils/.gitkeep",
    "chatbot/tests/.gitkeep",

    # infra/
    "infra/docker/Dockerfile.backend",
    "infra/docker/Dockerfile.ai",
    "infra/docker/Dockerfile.chatbot",
    "infra/docker/Dockerfile.web",
    "infra/docker/nginx.conf",
    "infra/aws/ecs/.gitkeep",
    "infra/aws/rds/.gitkeep",
    "infra/aws/s3/.gitkeep",
    "infra/aws/cloudwatch/.gitkeep",
    "infra/aws/secrets-manager/.gitkeep",
    "infra/scripts/setup.sh",
    "infra/scripts/migrate.sh",
    "infra/scripts/seed.sh",
    "infra/monitoring/sentry.config.py",
    "infra/monitoring/cloudwatch.config.json",

    # scripts/
    "scripts/dev-up.sh",
    "scripts/dev-down.sh",
    "scripts/reset-db.sh",
    "scripts/seed-all.sh"
]

def create_structure():
    created = 0
    for path in paths:
        folder = os.path.dirname(path)
        if folder and not os.path.exists(folder):
            os.makedirs(folder, exist_ok=True)
        if not os.path.exists(path):
            with open(path, 'w', encoding='utf-8') as f:
                if path.endswith('.md'):
                    f.write(f'# {os.path.basename(path).replace(".md", "").replace("-", " ").title()}\n')
                elif path.endswith('.gitkeep'):
                    pass
                else:
                    f.write('')
            created += 1
    print(f"Created {created} files.")

if __name__ == "__main__":
    create_structure()
